api/urls.py
from django.urls import include, re_path
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from .views import (AddAvatarView, AvatarListView, ChangeAvatarView, DeleteAvatarView, FeedContentApiView,
                    GetPublicityStatusView, PreferencesViewSet,
                    RenderPrimaryAvatarView, SideBarApiView,
                    ReplyCommentApiView,
                    LikeCommentApiView, UnlikeCommentApiView,
                    BrowseCommentReplyApiView, RemoveCommentApiView, SearchResultsApiView,
                    TelegramOptInApiView, SearchResultsCountApiView, CommentDetailApiView, GoogleLogin,
                    obtain_token_from_firebase_token)

app_name = 'api'

preferences_router = routers.SimpleRouter()
preferences_router.register(r'user', PreferencesViewSet, basename='user') 


router = routers.DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    re_path(r'^avatar/render_primary/(?P<user>[\w\d\@\.\-_]+)/(?P<size>[\d]+)/$',
            RenderPrimaryAvatarView.as_view(), name='render_primary'),
    re_path(r'^avatar/add/$', AddAvatarView.as_view(), name='add_avatar'),
    re_path(r'^avatar/all/$', AvatarListView.as_view(), name='all_avatars'),
    re_path(r'^avatar/change/$', ChangeAvatarView.as_view(),
            name='change_avatar'),
    re_path(r'^avatar/delete/$', DeleteAvatarView.as_view(),
            name='delete_avatar'), 

    re_path(r'^preferences/', include(preferences_router.urls)),

    re_path(r'^auth/token/$', obtain_jwt_token),
    re_path(r'^auth/refresh-token/$', refresh_jwt_token),
    re_path(r'^auth/firebase-token/$', obtain_token_from_firebase_token),
    
    re_path(r'^rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    
    re_path(r'^rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^rest-auth/google/$', GoogleLogin.as_view(), name='google_login'),

    re_path(r'^moogter_bot/', include('moogter_bot.urls')),

    re_path(r'^fcm-django/', include(router.urls)),

    re_path(r'^(?P<version>(v1))/moogt/', include('moogts.urls')),
    re_path(r'^(?P<version>(v1))/invitation/', include('invitations.urls')),
    re_path(r'^(?P<version>(v1|v2))/argument/', include('arguments.urls')),
    re_path(r'^(?P<version>(v1))/user/', include('users.urls')),
    re_path(r'^(?P<version>(v1))/poll/', include('polls.urls')),
    re_path(r'^(?P<version>(v1|v2))/view/', include('views.urls')),
    re_path(r'^(?P<version>(v1))/chat/', include('chat.urls')),

    re_path(r'^(?P<version>(v1))/publicity_status/all/$', GetPublicityStatusView.as_view(),
            name='list_publicity_status'),

    re_path(r'^(?P<version>(v1))/sidebar/$',
            SideBarApiView.as_view(), name="sidebar_view"),

    re_path(r'^(?P<version>(v1))/feed/$',
            FeedContentApiView.as_view(), name='feed_content'),

    re_path(r'^(?P<version>(v1))/comment/reply/$',
            ReplyCommentApiView.as_view(), name='reply_comment'),
    re_path(r'^(?P<version>(v1))/comment/reply/all/(?P<pk>\d+)/$', BrowseCommentReplyApiView.as_view(),
            name='browse_comment_replies'),
    re_path(r'^(?P<version>(v1))/comment/like/(?P<pk>\d+)/$',
            LikeCommentApiView.as_view(), name='like_comment'),
    re_path(r'^(?P<version>(v1))/comment/unlike/(?P<pk>\d+)/$',
            UnlikeCommentApiView.as_view(), name='unlike_comment'),
    re_path(r'^(?P<version>(v1))/comment/remove/(?P<pk>\d+)/$',
            RemoveCommentApiView.as_view(), name='remove_comment'),
    re_path(r'^(?P<version>(v1))/comment/detail/(?P<pk>\d+)/$',
            CommentDetailApiView.as_view(), name='comment_detail'),

    re_path(r'^(?P<version>(v1))/search/$',
            SearchResultsApiView.as_view(), name='search_results'),
    re_path(r'^(?P<version>(v1))/search/count/$',
            SearchResultsCountApiView.as_view(), name='search_results_count'),
    re_path(r'^(?P<version>(v1))/telegram/opt-in/$',
            TelegramOptInApiView.as_view(), name='telegram_opt_in'),
]

moogts/urls.py
from django.urls import re_path

from moogts.views import (MoogtListView, AcceptMoogtView,
                          MoogtCreateView, MoogtReportApiView, MyMoogtListApiView,
                          FollowingMoogtListApiView, LastOpenedMoogtApiView,
                          MoogtDetailView, FollowMoogtAPIView, GetUsersFollowingMoogtApiView,
                          ShareMoogt, UpdateMoogtPublicityStatusView,
                          EndMoogtView, MoogtSuggestionApiView,
                          MoogtSuggestionActionApiView, MoogtSuggestionListApiView,
                          UploadBannerApiView, HasLiveMoogtsView, UpdateMoogtApiView, UpdateAllSuggestionsApiView,
                          MakeCardRequestApiView, CardRequestActionApiView, MakeEndMoogtRequestApiView,
                          EndMoogtRequestActionApiView, QuitMoogtApiView, GetBundleActivitiesApiView,
                          MakePauseMoogtRequestApiView, PauseMoogtRequestActionApiView, MakeResumeMoogtRequestApiView,
                          ResumeMoogtRequestActionApiView, MakeDeleteMoogtRequestApiView,
                          DeleteMoogtRequestActionApiView, GetMoogtHighlightsApiView, MakeMoogtDonationApiView,
                          ListDonationsApiView)

app_name = 'moogts'

urlpatterns = [
    re_path(r'^all/$', MoogtListView.as_view(), name='list'),
    re_path(r'^accept/(?P<pk>\d+)/$', AcceptMoogtView.as_view(), name='accept'),
    re_path(r'^create/$', MoogtCreateView.as_view(), name='create'),
    re_path(r'^banner/upload/$', UploadBannerApiView.as_view(),
            name='upload_banner'),
    re_path(r'^my/$', MyMoogtListApiView.as_view(), name='my_moogt_list'),
    re_path(r'^followings/$', FollowingMoogtListApiView.as_view(),
            name='following_moogt_list'),
    re_path(r'^last-opened/$', LastOpenedMoogtApiView.as_view(),
            name='last_opened_moogt'),
    re_path(r'^detail/(?P<pk>\d+)/$', MoogtDetailView.as_view(), name='detail'),
    re_path(r'^follow/(?P<pk>\d+)/$',
            FollowMoogtAPIView.as_view(), name='follow_moogt'),
    re_path(r'^following/user/(?P<pk>\d+)/$',
            GetUsersFollowingMoogtApiView.as_view(), name='users_following'),
    re_path(r'^share/(?P<pk>\d+)/$', ShareMoogt.as_view(), name='share_moogt'),
    re_path(r'^update-publicity/$', UpdateMoogtPublicityStatusView.as_view(),
            name='update_moogt_publicity'),
    re_path(r'^update/(?P<pk>\d+)/$',
            UpdateMoogtApiView.as_view(), name='update_moogt'),
    re_path(r'^report/(?P<pk>\d+)/$',
            MoogtReportApiView.as_view(), name='report_moogt'),
    re_path(r'^end/(?P<pk>\d+)/$', EndMoogtView.as_view(), name='end_moogt'),
    re_path(r'^suggestion/create/$', MoogtSuggestionApiView.as_view(),
            name='create_moogt_suggestion'),
    re_path(r'^suggestion/change/$', MoogtSuggestionActionApiView.as_view(),
            name='update_moogt_suggestion'),
    re_path(r'^suggestion/change/all/(?P<pk>\d+)/$',
            UpdateAllSuggestionsApiView.as_view(),
            name='update_all_moogt_suggestion'),
    re_path(r'^suggestion/all/(?P<pk>\d+)/$',
            MoogtSuggestionListApiView.as_view(), name='list_moogt_suggestion'),
    re_path(r'^has-moogts/$', HasLiveMoogtsView.as_view(),
            name='has_live_moogts'),
    re_path(r'^request/card/(?P<pk>\d+)/$',
            MakeCardRequestApiView.as_view(), name='request_card'),
    re_path(r'^request/card/action/(?P<pk>\d+)/$',
            CardRequestActionApiView.as_view(), name='card_request_action'),
    re_path(r'^request/end/(?P<pk>\d+)/$',
            MakeEndMoogtRequestApiView.as_view(), name='request_end_moogt'),
    re_path(r'^request/end/action/(?P<pk>\d+)/$', EndMoogtRequestActionApiView.as_view(),
            name='end_moogt_request_action'),
    re_path(r'^request/pause/(?P<pk>\d+)/$',
            MakePauseMoogtRequestApiView.as_view(), name='request_pause_moogt'),
    re_path(r'^request/pause/action/(?P<pk>\d+)/$', PauseMoogtRequestActionApiView.as_view(),
            name='pause_moogt_request_action'),
    re_path(r'^request/resume/(?P<pk>\d+)/$',
            MakeResumeMoogtRequestApiView.as_view(), name='request_resume_moogt'),
    re_path(r'^request/resume/action/(?P<pk>\d+)/$', ResumeMoogtRequestActionApiView.as_view(),
            name='resume_moogt_request_action'),
    re_path(r'^request/delete/(?P<pk>\d+)/$',
            MakeDeleteMoogtRequestApiView.as_view(), name='request_delete_moogt'),
    re_path(r'^request/delete/action/(?P<pk>\d+)/$', DeleteMoogtRequestActionApiView.as_view(),
            name='delete_moogt_request_action'),
    re_path(r'^highlights/(?P<pk>\d+)/$',
            GetMoogtHighlightsApiView.as_view(), name='get_moogt_highlights'),
    re_path(r'^donate/(?P<pk>\d+)/$',
            MakeMoogtDonationApiView.as_view(), name='make_moogt_donation'),
    re_path(r'^donate/all/(?P<pk>\d+)/$',
            ListDonationsApiView.as_view(), name='list_moogt_donations'),
    re_path(r'^quit/(?P<pk>\d+)/$',
            QuitMoogtApiView.as_view(), name='quit_moogt'),
    re_path(r'^bundle/(?P<pk>\d+)/$',
            GetBundleActivitiesApiView.as_view(), name='bundle_activities')
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read,
            name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$',
            views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$',
            views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count,
            name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count,
            name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list,
            name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list,
            name='live_all_notification_list'),
    pattern(r'^api/mark_all_as_read', views.live_mark_all_as_read,
            name='live_mark_all_as_read'),
    pattern(r'^api/mark_as_read/(?P<pk>\d+)/$', views.live_mark_as_read,
            name='live_mark_as_read'),
    pattern(r'^api/mark-messages-as-read/$',
            views.live_mark_messages_as_read, name='live_mark_messages_as_read'),
]

app_name = 'notifications'

users/urls.py
from django.urls import re_path

from .views import (BlockUserApiView, BlockedUsersListApiView, GetUsernamesApiView,
                    FollowUserApiView, ReportAccountApiView, UserProfileApiView, GetSubscriptionInfo,
                    EditProfileApiView, LoggedInProfileView,
                    AnonymousProfileView, FollowUserView,
                    GetUsernamesAjaxView, UsersListApiView, RemoveProfileImagesApiView,
                    UserDetailApiView, RecommendedAccountsApiView,
                    GetProfileItemsCountApiView, RefillWalletApiView, ProfilePhotoUploadApiView,
                RegisterWithPhoneApiView,)

app_name = 'users'

urlpatterns = [
    re_path(r'^user/(?P<username>.+)/$', AnonymousProfileView.as_view(),
            name='anonymous_profile'),
    re_path(r'^profile/$', LoggedInProfileView.as_view(),
            name='logged_in_profile'),
    re_path(r'^follow/$', FollowUserView.as_view(), name='legacy_follow_user'),
    re_path(r'get_usernames_legacy/$', GetUsernamesAjaxView.as_view(),
            name='get_usernames_ajax'),

    re_path(r'^get_usernames/$',
            GetUsernamesApiView.as_view(), name='get_usernames'),
    re_path(r'^(?P<pk>\d+)/$',
            UserDetailApiView.as_view(), name='user_detail'),

    re_path(r'^follow/(?P<pk>\d+)/$',
            FollowUserApiView.as_view(), name='follow_user'),

    re_path(r'^block/(?P<pk>\d+)/$',
            BlockUserApiView.as_view(), name='block_user'),
    re_path(r'^block/all/$', BlockedUsersListApiView.as_view(),
            name='blocked_users_list'),

    re_path(r'^profile/(?P<pk>\d+)/$',
            UserProfileApiView.as_view(), name='profile_user'),
    re_path(r'^profile/count/(?P<pk>\d+)/$',
            GetProfileItemsCountApiView.as_view(), name='profile_items_count'),
    re_path(r'^profile/photo/remove/$',
            RemoveProfileImagesApiView.as_view(), name='remove_profile_images'),

    re_path(r'^edit/$', EditProfileApiView.as_view(), name='edit_user'),
    re_path(r'all/$', UsersListApiView.as_view(), name='users_list'),
    re_path(r'^recommended/$', RecommendedAccountsApiView.as_view(),
            name='recommended_accounts'),
    re_path(r'^wallet/refill/$', RefillWalletApiView.as_view(),
            name='refill_wallet'),
    re_path(r'^subscriptions/$', GetSubscriptionInfo.as_view(),
            name='subscription_accounts'),

    re_path(r'^profile/upload/$', ProfilePhotoUploadApiView.as_view(),
            name='upload_profile_photo'),

    re_path(r'^report/(?P<pk>\d+)/$', ReportAccountApiView.as_view(),
            name='report_account'),
    re_path(r'^register-with-phone/$', RegisterWithPhoneApiView.as_view(), 
            name='register_with_phone'),
]

meda/forms.py
from django import forms
from moogts.models import Moogt
from arguments.models import Argument
from django.urls import reverse, reverse_lazy


class MoogtForm(forms.ModelForm):

    class Meta:
        model = Moogt
        fields = ['resolution']
        widgets = {
            'resolution': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ArgumentForm(forms.ModelForm):

    class Meta:
        model = Argument
        fields = ['argument']
        widgets = {
            'argument': forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
        }


class MoogtAdditionalForm(forms.Form):
    argument = forms.CharField(widget=forms.Textarea(
        attrs={'rows': 4, 'class': 'form-control'}), label='Opening argument', max_length=500, required=True)

meda/views.py
from django.http import HttpResponse
from django.shortcuts import redirect

from notifications.signals import notify


def index(request):
    """A stub index view."""
    return redirect('meda:browse')


def profile(request):
    """A stub profile page for a user. A custom profile view is required for the
    proper functioning of the allauth app.
    """
    return HttpResponse("You've reached the profile page.")


def send_notifications(sender, recipient, verb, target, send_email=True, action_object=None):
    notify.send(
        recipient=recipient,
        sender=sender,
        verb=verb,
        target=target,
        send_email=send_email,
        action_object=action_object)

meda/templates/meda/_argument_card.html
{% load humanize %}
{% load avatar_tags %}
{% load users_tags %}
{% load comments %}

<article class="{% if argument.func_empty %}mgt-card-missed{% else %}mgt-card{% endif %}">
    <div class="mgt-card-container">
        <div class="sc-author-time">
            {{ argument.get_created_at|naturaltime }}
        </div>
        <hr>
        <div class="mgt-mgtr-ctnr">
            <div
                class="mgt-mgtr {% if argument.get_user == argument.get_moogt.get_proposition %} mgt-mgtr-left {% else %} mgt-mgtr-right {% endif %}">
                <div class="mgt-author-pic-container">
                    <a href="{% url 'users:anonymous_profile' argument.get_user.username %}">
                        {% avatar argument.get_user class="mgt-author-pic" %}
                    </a>
                </div>
                <div class="mgtr-name">
                    <b>{% moogter_user_display argument.get_user %}</b>
                </div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <div class="mgt-body">
            {% if argument.func_empty %}
            <p>
                <div class="mgt-missed-turn">
                    Missed turn.
                </div>
            </p>
            {% else %}
            <p>
                {{ argument.get_argument }}
            </p>
            <hr>
            {% if argument.get_moogt.func_has_started %}
            <div class="voting-wrapper" data-url="{% url 'meda:upvote_downvote' %}">
                <span class="num-votes" id="num_upvotes_{{ argument.id }}">{{ argument.stats.get_upvotes.count }}</span>
                <a href="#" id="upvote_{{ argument.id }}"
                    class="vote-btn {% if disallow_voting %} inactive {% endif %}">
                    <i class="fas fa-plus-circle fa-lg"></i></a>
                <a href="#" id="downvote_{{ argument.id }}"
                    class="vote-btn {% if disallow_voting %} inactive {% endif %}">
                    <i class="fas fa-minus-circle fa-lg"></i></a>
                <span class="num-votes" id="num_downvotes_{{ argument.id }}">{{ argument.stats.get_downvotes.count }}</span>
            </div>
            {% endif %}
            {% endif %}
            {% get_comment_count for argument as comment_count %}
            <div class='mgt-comment-count'>
                <a href="#" class="load-comments-btn" id="load_comments_{{ argument.id }}"><i class="fa fa-comments"
                        aria-hidden="true"></i>&nbsp;{{ comment_count }}</a>
            </div>
            <div class="mgt-comments-wrapper" id="comments_wrapper_{{ argument.id }}" data-url="{% url 'meda:get_comments_ajax' %}"></div>
        </div>
    </div>
</article>

meda/templates/meda/_comment_card.html
{% load i18n %}
{% load comments %}
{% load comments_xtd %}
{% load avatar_tags %}
{% load users_tags %}
{% load humanize %}

<div id="c{{ comment.id }}" class="mgt-comment-card-cntr media">
    <a name="c{{ comment.id }}"></a>
    <div class="mgt-comment-author-pic-container">
        <a href="{% url 'users:anonymous_profile' comment.user.username %}">
            {% avatar comment.user class="mgt-comment-author-pic" %}
        </a>
    </div>
    <div class="media-body">
        <div class="comment pb-3">
            <h6 class="mb-1 small d-flex">
                    <span class="mr-auto p-2">{% moogter_user_display comment.user %}</span>
                    <span class="p-2">{{ comment.submit_date|naturaltime }}</span>
            </h6>
            <div class="content mgt-comment-content">
                {% if comment.is_removed %}
                <p class="text-muted">{% trans "This comment has been removed." %}</p>
                {% else %}
                    {% include "includes/django_comments_xtd/comment_content.html" with content=comment.comment %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

meda/templates/meda/_invitation_modal.html
<div class="modal fade" id="invitationModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Invite someone</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="id_invitation_modal_body" class="modal-body">
          <div class="form-group">
                <label for="id_modal_invitees">Invite Someone:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                    </div>
                    <select id="id_modal_invitees"
                        multiple="multiple"
                        data-url="{% url 'users:get_usernames_ajax' %}"
                        name="invitees">
                    </select>
                </div>
          </div>
      </div>
      <div class="modal-footer">
        <input id="id_moogt_id_field" type="hidden" value={{moogt.id}}>
        <button type="button" class="btn btn-outline-secondary" data-url="{% url 'meda:invite_moogter' %}"
          id="id_invite_moogter" data-dismiss="modal">Invite</button>
      </div>
    </div>
  </div>
</div>

meda/templates/meda/_moogt_card.html
{% load humanize %}
{% load avatar_tags %}
{% load users_tags %}

<article class="mgt-card">
    <div class="mgt-card-container">
        <div class="sc-author-time">
            <p style="text-align:left;">
                {{ moogt.get_created_at|naturaltime }}
                <span style="float:right;">
                    {{ moogt.stats.get_view_count }} view {{ moogt.stats.get_view_count|pluralize }}
                </span>
            </p>
        </div>

        <hr>

        <div class="mgt-mgtr-ctnr">

            <div class="mgt-mgtr mgt-mgtr-left">
                <div class="mgt-author-pic-container">
                    <a href="{% url 'users:anonymous_profile' moogt.get_proposition.username %}">
                        {% avatar moogt.get_proposition 60 class="mgt-author-pic" %}
                    </a>
                </div>
                <div class="mgtr-name">
                    <b>{% moogter_user_display moogt.get_proposition %}</b>
                </div>
            </div>

            {% if moogt.get_opposition %}
            <div class="mgt-mgtr mgt-mgtr-right">
                <div class="mgt-author-pic-container">
                    <a href="{% url 'users:anonymous_profile' moogt.get_opposition.username %}">
                        {% avatar moogt.get_opposition 60 class="mgt-author-pic" %}
                    </a>
                </div>
                <div class="mgtr-name">
                    <b>{% moogter_user_display moogt.get_opposition %}</b>
                </div>
            </div>
            {% endif %}
            <div style="clear: both;"></div>
        </div>
        <div class="mgt-body">
            <h4><a class="mgt-link" href="{% url 'meda:detail' moogt.id %}">{{ moogt.get_resolution }}</a></h4>
            <p>
                <!-- Show the first argument, it should be by the proposition. -->
                {{ moogt.arguments.all.0.argument }}
            </p>
        </div>
    </div>
    {% if moogt.stats.func_has_any_votes %}
    <div class="mgt-progress">
        <div class="left" style="width: {{ moogt.stats.func_proposition_win_percent }}%"></div>
        <div class="right" style="width: {{ moogt.stats.func_opposition_win_percent }}%"></div>
    </div>
    {% endif %}
</article>

meda/templates/meda/_nav_bar.html
{% load static %}
{% load notifications_tags %}

<nav class="moogt-nav navbar-expand-lg navbar-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3"><a class="navbar-brand" style="margin-right:0px;" href="{% url 'index' %}">
                <img style="max-width: 100%; margin-top: -18%; " src="{% static 'favicon/moogter_logo.png' %}" alt="Moogter">
            </a></div>
            <div class="col-md-6">
                <div class="navbar-nav">
                    <form class="form-inline" method="get" action="{% url 'meda:search' %}">
                        <div class="input-group">
                            <input type="text" class="form-control search-box" placeholder="Search"
                                name="q" aria-label="Username" aria-describedby="basic-addon1">
                            <div class="input-group-append">
                                <button class="btn btn-default search-btn" type="submit" style="background-color: buttonface;">
                                    <i class="fa fa-search"
                                        aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3">
                {% if user.is_authenticated %}
                <div class="float-right">
                    <div class="notifications dropdown btn-group float-left">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            <i class="fa fa-bell" aria-hidden="true"></i> {% live_notify_badge %}
                        </a>
                        <ul class="live_notify_list dropdown-menu dropdown-menu-right">
                            <div class="dropdown-header">
                                <div class="row">
                                    No notifications.
                                </div>
                            </div>
                        </ul>
                    </div>
                    <div class="dropdown btn-group float-left">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            <i class="fa fa-user-circle" aria-hidden="true"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href={% url 'users:logged_in_profile' %}>Profile</a>
                            <a class="dropdown-item" href={% url 'users:user_preferences_section' section='email' %}>Preferences</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

meda/templates/meda/_side_pane.html
{% load static %}
{% load compile_static %}
{% load avatar_tags %}
{% load users_tags %}


<link rel="stylesheet" type="text/css" href="{% static 'meda/sidepane.scss'|compile %}" />

<div class="side-pane mt-10 sticky-top">
    <div class="mgt-author-pic-container">
        <a href="{% url 'users:logged_in_profile' %}">
            {% avatar user class="mgt-author-pic" %}
        </a>
    </div>
    <div class="user-name">
        {% if user.is_authenticated %}
        <h6>{% moogter_user_display user %}</h6>
        {% else %}
        <a href="{% url 'account_login' %}">Sign in</a> or <a href="{% url 'account_signup' %}">Sign up</a>
        {% endif %}
    </div>

    <div class="side-pane-info">
        <span class="side-pane-number-container">
            <b>
                <span id="id_xp_pts">{{ user.profile.xp|default:"0" }}</span>
            </b>
        </span>
        <span class="side-pane-label"><b>Experience Points</b></span>
    </div>

    <div class="side-pane-followers">
        <div class="float-left">
            <a href="{% url 'users:logged_in_profile' %}#followers">
                <div class="stat-number">
                <b>{{ user.followers.count }}</b>
                </div>
                <div>
                    <b>Followers</b>
                </div>
            </a>

        </div>
        <div class="float-right">
            <a href="{% url 'users:logged_in_profile' %}#followings">
                <div class="stat-number">
                <b>{{ user.followings.count }}</b>
                </div>
                <div>
                    <b>Following</b>
                </div>
            </a>
        </div>
        <div style="clear: both;"></div>
    </div>
    <hr>
    <div class="side-pane-nav"><b>Saved Moogts</b></div>
    <div class="side-pane-nav"><b>Public Prompts</b></div>
    <div class="side-pane-nav"><b>Moogt History</b></div>
</div>