api/urls.py
from django.urls import include, re_path
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from .views import (AddAvatarView, AvatarListView, ChangeAvatarView, DeleteAvatarView, FeedContentApiView,
                    GetPublicityStatusView, PreferencesViewSet,
                    RenderPrimaryAvatarView, SideBarApiView,
                    ReplyCommentApiView,
                    LikeCommentApiView, UnlikeCommentApiView,
                    BrowseCommentReplyApiView, RemoveCommentApiView, SearchResultsApiView,
                    TelegramOptInApiView, SearchResultsCountApiView, CommentDetailApiView, GoogleLogin,
                    obtain_token_from_firebase_token)

app_name = 'api'

preferences_router = routers.SimpleRouter()
preferences_router.register(r'user', PreferencesViewSet, basename='user') 


router = routers.DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)

urlpatterns = [
    re_path(r'^avatar/render_primary/(?P<user>[\w\d\@\.\-_]+)/(?P<size>[\d]+)/$',
            RenderPrimaryAvatarView.as_view(), name='render_primary'),
    re_path(r'^avatar/add/$', AddAvatarView.as_view(), name='add_avatar'),
    re_path(r'^avatar/all/$', AvatarListView.as_view(), name='all_avatars'),
    re_path(r'^avatar/change/$', ChangeAvatarView.as_view(),
            name='change_avatar'),
    re_path(r'^avatar/delete/$', DeleteAvatarView.as_view(),
            name='delete_avatar'), 

    re_path(r'^preferences/', include(preferences_router.urls)),

    re_path(r'^auth/token/$', obtain_jwt_token),
    re_path(r'^auth/refresh-token/$', refresh_jwt_token),
    re_path(r'^auth/firebase-token/$', obtain_token_from_firebase_token),
    
    re_path(r'^rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    
    re_path(r'^rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^rest-auth/google/$', GoogleLogin.as_view(), name='google_login'),

    re_path(r'^moogter_bot/', include('moogter_bot.urls')),

    re_path(r'^fcm-django/', include(router.urls)),

    re_path(r'^(?P<version>(v1))/moogt/', include('moogts.urls')),
    re_path(r'^(?P<version>(v1))/invitation/', include('invitations.urls')),
    re_path(r'^(?P<version>(v1|v2))/argument/', include('arguments.urls')),
    re_path(r'^(?P<version>(v1))/user/', include('users.urls')),
    re_path(r'^(?P<version>(v1))/poll/', include('polls.urls')),
    re_path(r'^(?P<version>(v1|v2))/view/', include('views.urls')),
    re_path(r'^(?P<version>(v1))/chat/', include('chat.urls')),

    re_path(r'^(?P<version>(v1))/publicity_status/all/$', GetPublicityStatusView.as_view(),
            name='list_publicity_status'),

    re_path(r'^(?P<version>(v1))/sidebar/$',
            SideBarApiView.as_view(), name="sidebar_view"),

    re_path(r'^(?P<version>(v1))/feed/$',
            FeedContentApiView.as_view(), name='feed_content'),

    re_path(r'^(?P<version>(v1))/comment/reply/$',
            ReplyCommentApiView.as_view(), name='reply_comment'),
    re_path(r'^(?P<version>(v1))/comment/reply/all/(?P<pk>\d+)/$', BrowseCommentReplyApiView.as_view(),
            name='browse_comment_replies'),
    re_path(r'^(?P<version>(v1))/comment/like/(?P<pk>\d+)/$',
            LikeCommentApiView.as_view(), name='like_comment'),
    re_path(r'^(?P<version>(v1))/comment/unlike/(?P<pk>\d+)/$',
            UnlikeCommentApiView.as_view(), name='unlike_comment'),
    re_path(r'^(?P<version>(v1))/comment/remove/(?P<pk>\d+)/$',
            RemoveCommentApiView.as_view(), name='remove_comment'),
    re_path(r'^(?P<version>(v1))/comment/detail/(?P<pk>\d+)/$',
            CommentDetailApiView.as_view(), name='comment_detail'),

    re_path(r'^(?P<version>(v1))/search/$',
            SearchResultsApiView.as_view(), name='search_results'),
    re_path(r'^(?P<version>(v1))/search/count/$',
            SearchResultsCountApiView.as_view(), name='search_results_count'),
    re_path(r'^(?P<version>(v1))/telegram/opt-in/$',
            TelegramOptInApiView.as_view(), name='telegram_opt_in'),
]

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read,
            name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$',
            views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$',
            views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count,
            name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count,
            name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list,
            name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list,
            name='live_all_notification_list'),
    pattern(r'^api/mark_all_as_read', views.live_mark_all_as_read,
            name='live_mark_all_as_read'),
    pattern(r'^api/mark_as_read/(?P<pk>\d+)/$', views.live_mark_as_read,
            name='live_mark_as_read'),
    pattern(r'^api/mark-messages-as-read/$',
            views.live_mark_messages_as_read, name='live_mark_messages_as_read'),
]

app_name = 'notifications'

users/urls.py
from django.urls import re_path

from .views import (BlockUserApiView, BlockedUsersListApiView, GetUsernamesApiView,
                    FollowUserApiView, ReportAccountApiView, UserProfileApiView, GetSubscriptionInfo,
                    EditProfileApiView, LoggedInProfileView,
                    AnonymousProfileView, FollowUserView,
                    GetUsernamesAjaxView, UsersListApiView, RemoveProfileImagesApiView,
                    UserDetailApiView, RecommendedAccountsApiView,
                    GetProfileItemsCountApiView, RefillWalletApiView, ProfilePhotoUploadApiView,
                RegisterWithPhoneApiView,)

app_name = 'users'

urlpatterns = [
    re_path(r'^user/(?P<username>.+)/$', AnonymousProfileView.as_view(),
            name='anonymous_profile'),
    re_path(r'^profile/$', LoggedInProfileView.as_view(),
            name='logged_in_profile'),
    re_path(r'^follow/$', FollowUserView.as_view(), name='legacy_follow_user'),
    re_path(r'get_usernames_legacy/$', GetUsernamesAjaxView.as_view(),
            name='get_usernames_ajax'),

    re_path(r'^get_usernames/$',
            GetUsernamesApiView.as_view(), name='get_usernames'),
    re_path(r'^(?P<pk>\d+)/$',
            UserDetailApiView.as_view(), name='user_detail'),

    re_path(r'^follow/(?P<pk>\d+)/$',
            FollowUserApiView.as_view(), name='follow_user'),

    re_path(r'^block/(?P<pk>\d+)/$',
            BlockUserApiView.as_view(), name='block_user'),
    re_path(r'^block/all/$', BlockedUsersListApiView.as_view(),
            name='blocked_users_list'),

    re_path(r'^profile/(?P<pk>\d+)/$',
            UserProfileApiView.as_view(), name='profile_user'),
    re_path(r'^profile/count/(?P<pk>\d+)/$',
            GetProfileItemsCountApiView.as_view(), name='profile_items_count'),
    re_path(r'^profile/photo/remove/$',
            RemoveProfileImagesApiView.as_view(), name='remove_profile_images'),

    re_path(r'^edit/$', EditProfileApiView.as_view(), name='edit_user'),
    re_path(r'all/$', UsersListApiView.as_view(), name='users_list'),
    re_path(r'^recommended/$', RecommendedAccountsApiView.as_view(),
            name='recommended_accounts'),
    re_path(r'^wallet/refill/$', RefillWalletApiView.as_view(),
            name='refill_wallet'),
    re_path(r'^subscriptions/$', GetSubscriptionInfo.as_view(),
            name='subscription_accounts'),

    re_path(r'^profile/upload/$', ProfilePhotoUploadApiView.as_view(),
            name='upload_profile_photo'),

    re_path(r'^report/(?P<pk>\d+)/$', ReportAccountApiView.as_view(),
            name='report_account'),
    re_path(r'^register-with-phone/$', RegisterWithPhoneApiView.as_view(), 
            name='register_with_phone'),
]

users/forms.py
from allauth.account.forms import SignupForm
from .models import Profile


class MoogtMedaSignupForm(SignupForm):
    """A custom user creation form for MoogtMeda."""

    def save(self, request):
        user = super(MoogtMedaSignupForm, self).save(request)
        # Create an associated new profile for the user.
        new_profile = Profile()
        new_profile.user = user
        new_profile.save()
        return user

users/templates/users/_engagements.html
<ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Your number of views as an Proposition Moogter
        <span class="badge badge-primary badge-pill">
            {{ view_proposition_moogt | default:'0' }}
        </span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Your number of views as an Opposition Moogter
        <span class="badge badge-primary badge-pill">
            {{ view_opposition_moogt | default:'0' }}
        </span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Your total number of upvotes received
        <span class="badge badge-primary badge-pill">
            {{ upvote_argument | default:'0' }}
        </span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Your total number of downvotes received
        <span class="badge badge-primary badge-pill">
            {{ downvote_argument | default:'0' }}
        </span>
    </li>
</ul>

users/templates/users/preferences.html
{% extends 'meda/base.html' %}

{% block content %}
    <h2>Preferences</h2>
    <hr/>
    <div class="row">
        <div class="col-3">
            <div class="list-group">
                {% for s in registry.section_objects.values %}
                    <a class="list-group-item list-group-item-action {% if section.name == s.verbose_name %} active {% endif %}"
                       href="{% url 'users:user_preferences_section' section=s.name %}"
                    >{{ s.verbose_name | title }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col">
            <form action="" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-default" type="submit" style="background-color: buttonface;">Save</button>
            </form>
        </div>
    </div>

    <ul class="sections">

    </ul>


{% endblock %}

users/templates/users/profile.html
{% extends 'meda/base.html' %}

{% load meda_tags %}
{% load avatar_tags %}
{% load users_tags %}
{% load humanize %}
{% load static %}

{% block content %}
<h2>{% moogter_user_display profile.user %}</h2>
{% avatar profile.user %}
<br>

{% if is_self_profile %}
<a href="{% url 'avatar_change' %}">Change your avatar</a>
<br>
Email: {{ user.email }}
<br>
<a href="{% url 'account_email' %}">Change your email</a>
<br>

<hr>
<h2> Invitations: </h2>
<ul class="list-group">
    <li class="list-group-item list-group-item-secondary d-flex justify-content-between align-items-center">
        Invitations sent to you.
    </li>
    {% if profile.user.recieved_invitations.count > 0 %}
    {% for invitation in profile.user.recieved_invitations.all reversed %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {% moogter_user_display invitation.inviter %} invited you to join him for a Moogt.
        <a href="{% url 'meda:detail' invitation.moogt.id %}">
            Respond
        </a>
    </li>
    {% endfor %}
    {% else %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        You haven't recieved any invitations yet.
    </li>
    {% endif %}
    <li class="list-group-item list-group-item-secondary d-flex justify-content-between align-items-center">
        Invitations you sent.
    </li>
    {% if profile.user.sent_invitations.count > 0  %}
    {% for invitation in profile.user.sent_invitations.all reversed %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Invitation sent to {% moogter_user_display invitation.invitee %}.
    </li>
    {% endfor %}
    {% else %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        You haven't sent any invitations yet.
    </li>
    {% endif %}
</ul>

<hr>
<h2>Engagements Created:</h2>
<br>
So far you have earned <b>{{ profile.credit_pts }}</b> point{{ profile.credit_pts|pluralize }}
by creating the following engagement:
<br>
<br>
{% engagements_display profile.credit_pts_count %}

<hr>

<h2> Your activities: </h2>
<ul class="list-group">
    {% for activity in profile.activities.all reversed %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ activity.description }}
        {% if activity.href %}
        <a href="{{ activity.href }}">
            {{ activity.created_at|naturaltime }}
        </a>
        {% else %}
        {{ activity.created_at|naturaltime }}
        {% endif %}
        <span class="badge badge-primary badge-pill">+{{ activity.xp }} XPs</span>
    </li>
    {% endfor %}
</ul>

<hr>
<h2 id="followers">Followers:</h2>
<ul class="list-group">
    {% for follower in profile.user.followers.all %}
        <li class="list-group-item">{% moogter_user_display follower %}</li>
    {% endfor %}
</ul>

<hr>
<h2 id="followings">Following:</h2>
<ul class="list-group">
    {% for following in profile.user.followings.all %}
        <li class="list-group-item">{% moogter_user_display following %}</li>
    {% endfor %}
</ul>
{% elif can_follow_profile_owner %}
<a id="id_follow_button" data-followee-id="{{profile.user.id}}" data-url="{% url 'users:follow_user' %}"
    class="btn btn-outline-secondary">Follow</a>

{% endif %}
<br>
<br>
{% endblock content %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/input.js' %}"></script>
{% endblock scripts %}